listenbrainz/webserver/admin/__init__.py
from flask_admin import BaseView, AdminIndexView as IndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user
from flask import redirect, url_for, current_app

from listenbrainz.webserver import flash


class AuthMixin:
    """All admin views that shouldn't be available to the public must inherit from this."""

    def is_accessible(self):
        if current_user.is_authenticated:
            if current_user.musicbrainz_id in current_app.config['ADMINS']:
                return True
        return False

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            flash.error('You are not authorized to view the admin page.')
            return redirect(url_for('login.index'))

class AdminBaseView(AuthMixin, BaseView): pass
class AdminModelView(AuthMixin, ModelView): pass
class AdminIndexView(AuthMixin, IndexView): pass

listenbrainz/webserver/admin/views.py
from flask_admin import expose
from listenbrainz.webserver.admin import AdminIndexView


class HomeView(AdminIndexView):

    @expose('/')
    def index(self):
        return self.render('admin/home.html')

listenbrainz/webserver/login/__init__.py
from flask import redirect, url_for, current_app, request
from flask_login import LoginManager, UserMixin, current_user
from functools import wraps
import listenbrainz.db.user as db_user
from werkzeug.exceptions import Unauthorized
from listenbrainz.webserver.errors import APIUnauthorized

login_manager = LoginManager()
login_manager.login_view = 'login.index'


class User(UserMixin):
    def __init__(self, id, created, musicbrainz_id, auth_token, gdpr_agreed, login_id):
        self.id = id
        self.created = created
        self.musicbrainz_id = musicbrainz_id
        self.auth_token = auth_token
        self.gdpr_agreed = gdpr_agreed
        self.login_id = login_id

    def get_id(self):
        return self.login_id

    @classmethod
    def from_dbrow(cls, user):
        return cls(
            id=user['id'],
            created=user['created'],
            musicbrainz_id=user['musicbrainz_id'],
            auth_token=user['auth_token'],
            gdpr_agreed=user['gdpr_agreed'],
            login_id=user['login_id'],
        )

@login_manager.user_loader
def load_user(user_login_id):
    try:
        user = db_user.get_by_login_id(user_login_id)
    except Exception as e:
        current_app.logger.error("Error while getting user by login ID: %s", str(e), exc_info=True)
        return None
    if user:
        return User.from_dbrow(user)
    else:
        return None


def login_forbidden(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_anonymous:
            return redirect(url_for('index.index'))
        return f(*args, **kwargs)

    return decorated


def api_login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_authenticated:
            raise APIUnauthorized("You must be logged in to access this endpoint")
        return f(*args, **kwargs)

    return decorated

listenbrainz/webserver/views/follow.py
import ujson
from flask import Blueprint, render_template, current_app
from flask_login import current_user, login_required
from listenbrainz.domain import spotify
from listenbrainz.webserver.views.api_tools import parse_param_list
import listenbrainz.db.follow_list as db_follow_list


follow_bp = Blueprint("follow", __name__)

@follow_bp.route("/", defaults={"user_list": ""})
@follow_bp.route("/<user_list>")
@login_required
def follow(user_list):
    """ Allow an LB user to follow the stream of one or more other LB users.
    """

    if user_list:
        default_list = {'name': ''}
        follow_list_members = parse_param_list(user_list)
    else:
        default_list = db_follow_list.get_latest(creator=current_user.id)
        if not default_list:
            default_list = {'name': '', 'members': []}
        follow_list_members = [member['musicbrainz_id'] for member in default_list['members']]

    user_data = {
        "id": current_user.id,
        "name": current_user.musicbrainz_id,
        "auth_token": current_user.auth_token,
    }
    spotify_data = spotify.get_user_dict(current_user.id)
    props = {
        "user": user_data,
        "mode": "follow",
        "follow_list": follow_list_members,
        "spotify": spotify_data,
        "web_sockets_server_url": current_app.config["WEBSOCKETS_SERVER_URL"],
        "api_url": current_app.config["API_URL"],
        "save_url": "{}/1/follow/save".format(current_app.config["API_URL"]),
        "follow_list_name": default_list["name"],
        "follow_list_id": default_list["id"] if "id" in default_list else None,
    }

    return render_template(
        "index/follow.html",
        props=ujson.dumps(props),
        mode='follow',
        user=current_user,
        follow_list=follow_list_members,
        active_section='listens',
    )

listenbrainz/webserver/views/follow_api.py
import ujson
import listenbrainz.db.follow_list as db_follow_list
import listenbrainz.db.user as db_user

from flask import Blueprint, request, jsonify
from listenbrainz.webserver.decorators import crossdomain
from listenbrainz.webserver.rate_limiter import ratelimit
from listenbrainz.webserver.views.api_tools import log_raise_400, validate_auth_header
from listenbrainz.webserver.errors import APINotFound, APIForbidden, APIUnauthorized
from listenbrainz.db.exceptions import DatabaseException

follow_api_bp = Blueprint('follow_api_v1', __name__)

@follow_api_bp.route("/save", methods=["POST", "OPTIONS"])
@crossdomain(headers="Authorization, Content-Type")
@ratelimit()
def save_list():
    creator = validate_auth_header()
    raw_data = request.get_data()
    try:
        data = ujson.loads(raw_data.decode("utf-8"))
    except ValueError as e:
        log_raise_400("Cannot parse JSON document: %s" % str(e), raw_data)

    try:
        list_name = data['name']
        list_id = data['id']
        members = data['users']
    except KeyError as e:
        log_raise_400("JSON missing key: %s" % str(e))

    members = db_user.validate_usernames(members)
    if list_id is None:
        # create a new list
        try:
            list_id = db_follow_list.save(
                name=list_name,
                creator=creator['id'],
                members=[member['id'] for member in members],
            )
        except DatabaseException as e:
            raise APIForbidden("List with same name already exists.")
    else:

        # do some validation
        current_list = db_follow_list.get(list_id)
        if current_list is None:
            raise APINotFound("List not found: %d" % list_id)
        if current_list['creator'] != creator['id']:
            raise APIUnauthorized("You can only edit your own lists.")

        # update the old list
        db_follow_list.update(
            list_id=list_id,
            name=list_name,
            members=[member['id'] for member in members],
        )

    return jsonify({
        "code": 200,
        "message": "it worked!",
        "list_id": list_id,
    })

listenbrainz/webserver/views/index.py
import locale
import os
import requests
import subprocess

from brainzutils import cache
from datetime import datetime
from dateutil.relativedelta import relativedelta
from typing import List
from flask import Blueprint, render_template, current_app, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
from requests.exceptions import HTTPError
import ujson
from werkzeug.exceptions import Unauthorized, NotFound

import listenbrainz.db.user as db_user
from listenbrainz.db.exceptions import DatabaseException
from listenbrainz.domain import spotify
from listenbrainz import webserver
from listenbrainz.webserver import flash
from listenbrainz.webserver.timescale_connection import _ts
from listenbrainz.webserver.redis_connection import _redis
from listenbrainz.webserver.views.user import delete_user


index_bp = Blueprint('index', __name__)
locale.setlocale(locale.LC_ALL, '')

STATS_PREFIX = 'listenbrainz.stats' # prefix used in key to cache stats
CACHE_TIME = 10 * 60 # time in seconds we cache the stats
NUMBER_OF_RECENT_LISTENS = 50

@index_bp.route("/")
def index():

    # get total listen count
    try:
        listen_count = _ts.get_total_listen_count()
    except Exception as e:
        current_app.logger.error('Error while trying to get total listen count: %s', str(e))
        listen_count = None


    return render_template(
        "index/index.html",
        listen_count=listen_count,
    )


@index_bp.route("/import")
def import_data():
    if current_user.is_authenticated:
        return redirect(url_for("profile.import_data"))
    else:
        return current_app.login_manager.unauthorized()


@index_bp.route("/download")
def downloads():
    return redirect(url_for('index.data'))


@index_bp.route("/data")
def data():
    return render_template("index/data.html")


@index_bp.route("/contribute")
def contribute():
    return render_template("index/contribute.html")


@index_bp.route("/add-data")
def add_data_info():
    return render_template("index/add-data.html")


@index_bp.route("/import-data")
def import_data_info():
    return render_template("index/import-data.html")


@index_bp.route("/goals")
def goals():
    return render_template("index/goals.html")


@index_bp.route("/faq")
def faq():
    return render_template("index/faq.html")


@index_bp.route("/lastfm-proxy")
def proxy():
    return render_template("index/lastfm-proxy.html")


@index_bp.route("/roadmap")
def roadmap():
    return render_template("index/roadmap.html")


@index_bp.route("/current-status")
def current_status():

    load = "%.2f %.2f %.2f" % os.getloadavg()

    listen_count = _ts.get_total_listen_count()
    try:
        user_count = format(int(_get_user_count()), ',d')
    except DatabaseException as e:
        user_count = 'Unknown'

    listen_counts_per_day: List[dict] = []
    for delta in range(2):
        try:
            day = datetime.utcnow() - relativedelta(days=delta)
            day_listen_count = _redis.get_listen_count_for_day(day)
        except:
            current_app.logger.error("Could not get %s listen count from redis", day.strftime('%Y-%m-%d'), exc_info=True)
            day_listen_count = None
        listen_counts_per_day.append({
            "date": day.strftime('%Y-%m-%d'),
            "listen_count": format(day_listen_count, ',d') if day_listen_count else "0",
            "label": "today" if delta == 0 else "yesterday",
        })

    return render_template(
        "index/current-status.html",
        load=load,
        listen_count=format(int(listen_count), ",d") if listen_count else "0",
        user_count=user_count,
        listen_counts_per_day=listen_counts_per_day,
    )


@index_bp.route("/recent")
def recent_listens():

    recent = []
    for listen in _redis.get_recent_listens(NUMBER_OF_RECENT_LISTENS):
        recent.append({
                "track_metadata": listen.data,
                "user_name" : listen.user_name,
                "listened_at": listen.ts_since_epoch,
                "listened_at_iso": listen.timestamp.isoformat() + "Z",
            })

    spotify_user = {}
    if current_user.is_authenticated:
        spotify_user = spotify.get_user_dict(current_user.id)

    props = {
        "listens": recent,
        "mode": "recent",
        "spotify": spotify_user,
        "api_url": current_app.config["API_URL"],
    }

    return render_template("index/recent.html",
        props=ujson.dumps(props),
        mode='recent',
        active_section='listens')

@index_bp.route('/feed', methods=['GET', 'OPTIONS'])
@login_required
def feed():

    # TODO (param): remove this when feed feature is ready for release #feedfeatureflag
    if current_user.musicbrainz_id not in ['rob', 'iliekcomputers', 'mr_monkey', 'shivam-kapila', 'ishaanshah']:
        raise NotFound

    props = {
        'current_user': {
            'id': current_user.id,
            'name': current_user.musicbrainz_id,
            'auth_token': current_user.auth_token,
        }
    }
    return render_template('index/feed.html', props=ujson.dumps(props))



@index_bp.route('/agree-to-terms', methods=['GET', 'POST'])
@login_required
def gdpr_notice():
    if request.method == 'GET':
        return render_template('index/gdpr.html', next=request.args.get('next'))
    elif request.method == 'POST':
        if request.form.get('gdpr-options') == 'agree':
            try:
                db_user.agree_to_gdpr(current_user.musicbrainz_id)
            except DatabaseException as e:
                flash.error('Could not store agreement to GDPR terms')
            next = request.form.get('next')
            if next:
                return redirect(next)
            return redirect(url_for('index.index'))
        elif request.form.get('gdpr-options') == 'disagree':
            return redirect(url_for('profile.delete'))
        else:
            flash.error('You must agree to or decline our terms')
            return render_template('index/gdpr.html', next=request.args.get('next'))


@index_bp.route('/delete-user/<int:musicbrainz_row_id>')
def mb_user_deleter(musicbrainz_row_id):
    """ This endpoint is used by MusicBrainz to delete accounts once they
    are deleted on MusicBrainz too.

    See https://tickets.metabrainz.org/browse/MBS-9680 for details.

    Args: musicbrainz_row_id (int): the MusicBrainz row ID of the user to be deleted.

    Returns: 200 if the user has been successfully found and deleted from LB

    Raises:
        NotFound if the user is not found in the LB database
        Unauthorized if the MusicBrainz access token provided with the query is invalid
    """
    _authorize_mb_user_deleter(request.args.get('access_token', ''))
    user = db_user.get_by_mb_row_id(musicbrainz_row_id)
    if user is None:
        raise NotFound('Could not find user with MusicBrainz Row ID: %d' % musicbrainz_row_id)
    delete_user(user['musicbrainz_id'])
    return jsonify({'status': 'ok'}), 200


def _authorize_mb_user_deleter(auth_token):
    headers = {'Authorization': 'Bearer {}'.format(auth_token)}
    r = requests.get(current_app.config['MUSICBRAINZ_OAUTH_URL'], headers=headers)
    try:
        r.raise_for_status()
    except HTTPError:
        raise Unauthorized('Not authorized to use this view')

    data = {}
    try:
        data = r.json()
    except ValueError:
        raise Unauthorized('Not authorized to use this view')

    try:
        # 2007538 is the row ID of the `UserDeleter` account that is
        # authorized to access the `delete-user` endpoint
        if data['sub'] != 'UserDeleter' or data['metabrainz_user_id'] != 2007538:
            raise Unauthorized('Not authorized to use this view')
    except KeyError:
        raise Unauthorized('Not authorized to use this view')


def _get_user_count():
    """ Gets user count from either the brainzutils cache or from the database.
        If not present in the cache, it makes a query to the db and stores the
        result in the cache for 10 minutes.
    """
    user_count_key = "{}.{}".format(STATS_PREFIX, 'user_count')
    user_count = cache.get(user_count_key, decode=False)
    if user_count:
        return user_count
    else:
        try:
            user_count = db_user.get_user_count()
        except DatabaseException as e:
            raise
        cache.set(user_count_key, int(user_count), CACHE_TIME, encode=False)
        return user_count

listenbrainz/webserver/views/login.py
from flask import Blueprint, request, redirect, render_template, url_for, session, current_app
from flask_login import login_user, logout_user, login_required
from listenbrainz.webserver.login import login_forbidden, provider
from listenbrainz.webserver import flash
import listenbrainz.db.user as db_user
import time
import datetime

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
@login_forbidden
def index():
    return render_template('login/login.html')


@login_bp.route('/musicbrainz')
@login_forbidden
def musicbrainz():
    session['next'] = request.args.get('next')
    return redirect(provider.get_authentication_uri())


@login_bp.route('/musicbrainz/post')
@login_forbidden
def musicbrainz_post():
    """Callback endpoint."""
    if provider.validate_post_login():
        user = provider.get_user()
        db_user.update_last_login(user.musicbrainz_id)
        login_user(user, remember=True, duration=datetime.timedelta(current_app.config['SESSION_REMEMBER_ME_DURATION']))
        next = session.get('next')
        if next:
            return redirect(next)
    else:
        flash.error("Login failed.")
    return redirect(url_for('index.index'))


@login_bp.route('/logout/')
@login_required
def logout():
    session.clear()
    logout_user()
    return redirect(url_for('index.index'))

listenbrainz/webserver/templates/index/add-data.html
{%- extends 'base.html' -%}
{%- block title -%}Adding Data - ListenBrainz{%- endblock -%}
{%- block content -%}
  <h2 class="page-title">Adding your data to Listenbrainz</h2>
  {# Listen submission information #}
  <h3>Submitting Listens</h3>
  <p>
    These are programs that submit listens to ListenBrainz:
  </p>
  <ul>
    <li><em><a href="https://www.musicpd.org/">mpd</a></em>, a flexible, powerful, server-side application for playing music: <a href="https://github.com/kori/libra"><code>libra</code></a></li>
    <li><em><a href="https://wiki.gnome.org/Apps/Rhythmbox/">Rhythmbox</a></em>, a music playing application for GNOME: <a href="https://github.com/phw/rhythmbox-plugin-listenbrainz"><code>rhythmbox-plugin-listenbrainz</code></a></li>
    <li><em><a href="https://wiki.gnome.org/Apps/Lollypop">Lollypop</a></em>, a modern music player for GNOME</li>
    <li><em><a href="https://github.com/InputUsername/rescrobbled">Rescrobbled</a></em>, a universal Linux scrobbler for MPRIS enabled players</li>
    <li><em><a href="https://add0n.com/lastfm-scrobbler.html">Last.fm Scrobbler</a></em>, an extension for Firefox and Chrome</li>
    <li><em><a href="https://github.com/tgwizard/sls">Simple Last.fm Scrobbler</a></em>, for Android devices</li>
    <li><em><a href="https://github.com/amCap1712/vlc-listenbrainz-plugin">VLC Listenbrainz plugin</a></em>, cross-platform plugin for VLC player</li>
    <li><em><a href="https://web-scrobbler.com/">Web Scrobbler</a></em>, an extension for Firefox and Chromium-based browsers</li>
    <li><em><a href="https://play.google.com/store/apps/details?id=com.arn.scrobble">Pano Scrobbler</a></em>, a scrobbling application for Android Devices</li>
  </ul>

  <h3>Submitting via Spotify</h3>
  <p>
    ListenBrainz can automatically record listens from Spotify.
  </p>
  <p>
    Importing the same listens from two different sources such as Last.FM and Spotify may cause the creation
    of duplicates in your listen history. If you opt into our automatic Spotify import, you may notice duplications in
    the last 50 listens on Spotify.This is a temporary issue while we find better ways to deduplicate listens.
  </p>
  <p>
    <a href={{ url_for('profile.connect_spotify') }}>Connect your Spotify account to ListenBrainz.</a>
  </p>

  <h3>For advanced users</h3>
  <p>
    Developers are able to submit their listens to Listenbrainz via the Listenbrainz API. Information on how to do this
    can be found in the <a href="https://listenbrainz.readthedocs.io">API docs</a>
  </p>
{%- endblock -%}

listenbrainz/webserver/templates/index/contribute.html
{%- extends 'base.html' -%}
{%- block title -%}Contribute - ListenBrainz{%- endblock -%}
{%- block content -%}
  <h2 class="page-title">Contributing to ListenBrainz</h2>

  <h3>Donating</h3>
  <p>
    Listenbrainz is a free open source project that is not run for profit. If you would like to help the project out
    financially, consider <a href="https://metabrainz.org/donate">donating</a> to the MetaBrainz Foundation.
  </p>

  <h3>Developers</h3>
  <p>
     ListenBrainz is in its infancy and we need a lot of help to implement more features and to debug the existing
     features. If you feel like helping out and have experience with Python, Postgres and Redis,
     we'd love some help.
  </p>
  <p>
     Have a look at the <a href="https://github.com/metabrainz/listenbrainz-server">GitHub repository</a> for this
     project to get started. You may also consider heading to our IRC channel #metabrainz on irc.freenode.net and
     asking people there what should be worked on next. Finally, we also have a bug tracker that keeps track of our
     <a href="http://tickets.musicbrainz.org/browse/LB">current issues</a>.
  </p>

{%- endblock -%}

listenbrainz/webserver/templates/index/current-status.html
{%- extends 'base.html' -%}
{%- block title -%}Status - ListenBrainz{%- endblock -%}
{%- block content -%}

  <h2 class="page-title">Current status</h2>

  <div class="row">

    <div class="col-md-7 col-lg-8">
      <h3>ListenBrainz Stats</h3>
      <table class="table table-border table-condensed table-striped">
        <thead>
          <tr>
            <th>Description</th>
            <th>Number</th>
          </tr>
        </thead>
        <tbody>
        {% if user_count %}
          <tr>
            <td>Number of users</td>
            <td>{{ user_count }}</td>
          </tr>
        {% endif %}
        {% if listen_count %}
          <tr>
            <td>Number of listens</td>
            <td>{{ listen_count }}</td>
          </tr>
        {% endif %}
        {% if listen_counts_per_day %}
          {% for data in listen_counts_per_day %}
          <tr>
            <td>Number of listens submitted {{ data['label'] }} ({{ data['date'] }})</td>
            <td>{{ data['listen_count'] }}</td>
          </tr>
          {% endfor %}
        {% endif %}
        </tbody>
      </table>

      <p>
        If you are curious about the state of our Listen ingestion pipelines, you can
        create yourself a free account on our <a href="https://stats.metabrainz.org">infrastructure
        statistics site</a>. In particular,
        the
        <a href="https://stats.metabrainz.org/d/000000059/rabbitmq?orgId=1&refresh=1m&var-queue_vhost=%2Flistenbrainz">
        RabbitMQ ListenBrainz view</a> shows how many listens we are currently processing, and the number of incoming listens currently queued for processing.
      </p>

      <h3>load average</h3>

      <p>
        Current server load average
      </p>
      <div class="well">
         {{ load }}
      </div>

    </div>

    <div class="col-md-5 col-lg-4">

      <p style="text-align: center">
         <img style="border-radius: 15px;"
              src="{{ url_for('static', filename='img/selfie.jpg') }}"
              width="250"></img>
      </p>

      <p style="text-align: center">
         Our server doesn't have a selfie. :(</br>
         Have a monkey selfie instead!
         </p>
      </p>

    </div>

  </div>

{%- endblock -%}

listenbrainz/webserver/templates/index/gdpr.html
{% extends 'base.html' %}

{% block title %}Agree to Terms - ListenBrainz{% endblock %}

{% block content %}
  <h2 class="page-title">Agree to General Data Protection Regulations</h2>

  <div class="well bg-danger" style="max-width: 600px; margin: 0 auto;">
      <p class="text-danger" style="font-size: 16pt;">Important!</p>
      <p>
        By signing into ListenBrainz, you grant the MetaBrainz Foundation permission to include your listening history
        in data dumps we make publicly available under the
        <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 license</a>. None of your private information
        from your user profile will be included in these data dumps.
      </p>
      <p>
        Furthermore, you grant the MetaBrainz Foundation permission to process your listening history and include it
        in new open source tools such as recommendation engines that the ListenBrainz project is building. For details
        on processing your listening history, please see our <a href="https://metabrainz.org/gdpr">GDPR compliance
        statement</a>.
      <p>
      </p>
        If you change your mind about processing your listening history, you will need to
        <a href="{{ url_for('login.musicbrainz')}}">delete your ListenBrainz account</a>.
      </p>

    <form method="POST">
      <input type="radio" id="gdpr-agree" name="gdpr-options" value="agree" required>
      <label for="gdpr-agree">OK, I agree</label><br/>
      <input type="radio" id="gdpr-disagree" name="gdpr-options" value="disagree" required>
      <label for="gdpr-disagree">No, take me to the account deletion page</label><br/>
      {% if request.args.get('next') %}
        <input type="hidden" name="next" value="{{ request.args.get('next') }}"/>
      {% endif %}
    </div>
    <br/>
    <div class="well" style="max-width: 600px; margin: 0 auto;">
      <button type="submit" class="btn btn-primary btn-lg btn-block">Submit choice!</a>
    </div>
  </form>
{% endblock %}

listenbrainz/webserver/templates/index/import-data.html
{%- extends 'base.html' -%}
{%- block title -%}Importing Data - ListenBrainz{%- endblock -%}
{%- block content -%}
  <h2 class="page-title">Importing your data to Listenbrainz</h2>
  {# Last.fm import information #}
  <h3>Importing data from Last.fm</h3>

  <p>
     We encourage Last.fm users to save their listen histories to ListenBrainz.
  </p>
  <p>
    To help us test this service, please import your listen history from Last.fm. To proceed, you will need a
    MusicBrainz account.
  </p>
  <div class="well" style="max-width: 600px; margin: 0 auto;">
    <a href="{{ url_for('index.import_data') }}" class="btn btn-primary btn-lg btn-block">Import my listen history</a>
  </div>
{%- endblock -%}

listenbrainz/webserver/templates/index/index.html
{%- extends 'base.html' -%}
{%- block content -%}
  <div id="homepage" class="row">

    <div class="col-md-7 col-lg-8">
      <img src="{{ url_for('static', filename='img/logo_big.svg') }}" id="big-logo" />
      <h2 class="page-title">Welcome to ListenBrainz!</h2>
      <p>
        ListenBrainz keeps tracks of what music you listen to and
        provides you with insights into your listening habits. We're
        completely open-source and publish our data as open data.
      </p>
      <p>
        You can use ListenBrainz to track your music listening habits and
        share your taste with others using our visualizations. We also have an
        <a href="https://listenbrainz.readthedocs.io/en/production/dev/api/">API</a>
        if you want to do more with our data.
      </p>
      <p>
        To get started, you'll need to <a href="{{ url_for('login.index') }}">sign in</a> with
        a <a href="https://musicbrainz.org">MusicBrainz</a> account. If you don't have a MusicBrainz
        account, you can <a href="https://musicbrainz.org/register">create one</a>! Once you have an
        account, you can <a href="{{ url_for('profile.import_data') }}">import</a>
        data from Last.FM, <a href="{{ url_for('profile.connect_spotify') }}">connect your Spotify account</a>,
        or use one of the <a href="{{ url_for('index.add_data_info') }}">many players</a> which can
        automatically record your listening history.
      </p>
      <p>
        Need help? Ask our <a href="https://community.metabrainz.org/c/listenbrainz">community</a>!
      </p>
      <h2>About us</h2>
      <p>
        ListenBrainz is operated by the <a href="https://metabrainz.org">MetaBrainz Foundation</a>
        which has a long-standing history of curating, protecting and making music data available to the
        public. MetaBrainz commits itself to safe-guarding the ListenBrainz data indefinitely.
      </p>
      <p>
        We also make this incredibly useful data available to anyone who cares to play with it. You
        can use our API or our regular public <a href="https://listenbrainz.readthedocs.io/en/production/dev/listenbrainz-dumps/">data dumps</a>.
        All non-commercial use of this data is free, but commercial users are asked to <a href="https://metabrainz.org/supporters/account-type">support</a>
        us in order to help fund the project.
      </p>
      <p>
        For more information about this project and its goals, please take a look at our
        <a href="{{ url_for('index.goals') }}">goals page</a>.
      </p>
    </div>

    <div class="col-md-5 col-lg-4">

      <div id="stats" class="panel panel-default">
        <div class="panel-heading"><strong>Data Statistics</strong></div>
        <div class="panel-body">

          <table class="table table-collapsed">
            <thead>
              <tr>
                <th>Description</th>
                <th>Number</th>
              </tr>
            </thead>
            <tbody>
            {% if listen_count %}
              <tr>
                <td>Number of Listens</td>
                <td>{{ "{:,}".format(listen_count) }}</td>
              </tr>
            {% endif %}
            </tbody>
          </table>
          <p style="text-align: center">
            <small>updated every 5 minutes</small><br />
            <small><a href="{{ url_for('index.current_status') }}">more on the current status page</a></small>
          </p>
        </div>
      </div>

      <div id="twitter-block">
        <a class="twitter-timeline" data-dnt="true" data-lang="en" href="https://twitter.com/ListenBrainz" data-widget-id="640261552604643328" data-height="450px">Tweets by @ListenBrainz</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
    </div>
  </div>
{%- endblock -%}