listenbrainz/webserver/admin/__init__.py
from flask_admin import BaseView, AdminIndexView as IndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user
from flask import redirect, url_for, current_app

from listenbrainz.webserver import flash


class AuthMixin:
    """All admin views that shouldn't be available to the public must inherit from this."""

    def is_accessible(self):
        if current_user.is_authenticated:
            if current_user.musicbrainz_id in current_app.config['ADMINS']:
                return True
        return False

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            flash.error('You are not authorized to view the admin page.')
            return redirect(url_for('login.index'))

class AdminBaseView(AuthMixin, BaseView): pass
class AdminModelView(AuthMixin, ModelView): pass
class AdminIndexView(AuthMixin, IndexView): pass

listenbrainz/webserver/admin/views.py
from flask_admin import expose
from listenbrainz.webserver.admin import AdminIndexView


class HomeView(AdminIndexView):

    @expose('/')
    def index(self):
        return self.render('admin/home.html')

listenbrainz/webserver/login/__init__.py
from flask import redirect, url_for, current_app, request
from flask_login import LoginManager, UserMixin, current_user
from functools import wraps
import listenbrainz.db.user as db_user
from werkzeug.exceptions import Unauthorized
from listenbrainz.webserver.errors import APIUnauthorized

login_manager = LoginManager()
login_manager.login_view = 'login.index'


class User(UserMixin):
    def __init__(self, id, created, musicbrainz_id, auth_token, gdpr_agreed, login_id):
        self.id = id
        self.created = created
        self.musicbrainz_id = musicbrainz_id
        self.auth_token = auth_token
        self.gdpr_agreed = gdpr_agreed
        self.login_id = login_id

    def get_id(self):
        return self.login_id

    @classmethod
    def from_dbrow(cls, user):
        return cls(
            id=user['id'],
            created=user['created'],
            musicbrainz_id=user['musicbrainz_id'],
            auth_token=user['auth_token'],
            gdpr_agreed=user['gdpr_agreed'],
            login_id=user['login_id'],
        )

@login_manager.user_loader
def load_user(user_login_id):
    try:
        user = db_user.get_by_login_id(user_login_id)
    except Exception as e:
        current_app.logger.error("Error while getting user by login ID: %s", str(e), exc_info=True)
        return None
    if user:
        return User.from_dbrow(user)
    else:
        return None


def login_forbidden(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_anonymous:
            return redirect(url_for('index.index'))
        return f(*args, **kwargs)

    return decorated


def api_login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_authenticated:
            raise APIUnauthorized("You must be logged in to access this endpoint")
        return f(*args, **kwargs)

    return decorated

listenbrainz/webserver/views/follow.py
import ujson
from flask import Blueprint, render_template, current_app
from flask_login import current_user, login_required
from listenbrainz.domain import spotify
from listenbrainz.webserver.views.api_tools import parse_param_list
import listenbrainz.db.follow_list as db_follow_list


follow_bp = Blueprint("follow", __name__)

@follow_bp.route("/", defaults={"user_list": ""})
@follow_bp.route("/<user_list>")
@login_required
def follow(user_list):
    """ Allow an LB user to follow the stream of one or more other LB users.
    """

    if user_list:
        default_list = {'name': ''}
        follow_list_members = parse_param_list(user_list)
    else:
        default_list = db_follow_list.get_latest(creator=current_user.id)
        if not default_list:
            default_list = {'name': '', 'members': []}
        follow_list_members = [member['musicbrainz_id'] for member in default_list['members']]

    user_data = {
        "id": current_user.id,
        "name": current_user.musicbrainz_id,
        "auth_token": current_user.auth_token,
    }
    spotify_data = spotify.get_user_dict(current_user.id)
    props = {
        "user": user_data,
        "mode": "follow",
        "follow_list": follow_list_members,
        "spotify": spotify_data,
        "web_sockets_server_url": current_app.config["WEBSOCKETS_SERVER_URL"],
        "api_url": current_app.config["API_URL"],
        "save_url": "{}/1/follow/save".format(current_app.config["API_URL"]),
        "follow_list_name": default_list["name"],
        "follow_list_id": default_list["id"] if "id" in default_list else None,
    }

    return render_template(
        "index/follow.html",
        props=ujson.dumps(props),
        mode='follow',
        user=current_user,
        follow_list=follow_list_members,
        active_section='listens',
    )

listenbrainz/webserver/views/follow_api.py
import ujson
import listenbrainz.db.follow_list as db_follow_list
import listenbrainz.db.user as db_user

from flask import Blueprint, request, jsonify
from listenbrainz.webserver.decorators import crossdomain
from listenbrainz.webserver.rate_limiter import ratelimit
from listenbrainz.webserver.views.api_tools import log_raise_400, validate_auth_header
from listenbrainz.webserver.errors import APINotFound, APIForbidden, APIUnauthorized
from listenbrainz.db.exceptions import DatabaseException

follow_api_bp = Blueprint('follow_api_v1', __name__)

@follow_api_bp.route("/save", methods=["POST", "OPTIONS"])
@crossdomain(headers="Authorization, Content-Type")
@ratelimit()
def save_list():
    creator = validate_auth_header()
    raw_data = request.get_data()
    try:
        data = ujson.loads(raw_data.decode("utf-8"))
    except ValueError as e:
        log_raise_400("Cannot parse JSON document: %s" % str(e), raw_data)

    try:
        list_name = data['name']
        list_id = data['id']
        members = data['users']
    except KeyError as e:
        log_raise_400("JSON missing key: %s" % str(e))

    members = db_user.validate_usernames(members)
    if list_id is None:
        # create a new list
        try:
            list_id = db_follow_list.save(
                name=list_name,
                creator=creator['id'],
                members=[member['id'] for member in members],
            )
        except DatabaseException as e:
            raise APIForbidden("List with same name already exists.")
    else:

        # do some validation
        current_list = db_follow_list.get(list_id)
        if current_list is None:
            raise APINotFound("List not found: %d" % list_id)
        if current_list['creator'] != creator['id']:
            raise APIUnauthorized("You can only edit your own lists.")

        # update the old list
        db_follow_list.update(
            list_id=list_id,
            name=list_name,
            members=[member['id'] for member in members],
        )

    return jsonify({
        "code": 200,
        "message": "it worked!",
        "list_id": list_id,
    })

listenbrainz/webserver/views/profile.py
import listenbrainz.db.feedback as db_feedback
import listenbrainz.db.stats as db_stats
import listenbrainz.db.user as db_user
import listenbrainz.webserver.rabbitmq_connection as rabbitmq_connection
from listenbrainz.webserver.decorators import crossdomain
import os
import re
import ujson
import zipfile


from datetime import datetime
from flask import Blueprint, Response, render_template, request, url_for, \
    redirect, current_app, make_response, jsonify, stream_with_context
from flask_login import current_user, login_required
import spotipy.oauth2
from werkzeug.exceptions import NotFound, BadRequest, RequestEntityTooLarge, InternalServerError, Unauthorized
from listenbrainz.webserver.errors import APIBadRequest, APIServiceUnavailable, APINotFound
from werkzeug.utils import secure_filename

from listenbrainz import webserver
from listenbrainz.db.exceptions import DatabaseException
from listenbrainz.domain import spotify
from listenbrainz.webserver import flash
from listenbrainz.webserver.login import api_login_required
from listenbrainz.webserver.utils import sizeof_readable
from listenbrainz.webserver.views.feedback_api import _feedback_to_api
from listenbrainz.webserver.views.user import delete_user, _get_user, delete_listens_history
from listenbrainz.webserver.views.api_tools import insert_payload, validate_listen, \
    LISTEN_TYPE_IMPORT, publish_data_to_queue
from os import path, makedirs
from time import time

profile_bp = Blueprint("profile", __name__)

EXPORT_FETCH_COUNT = 5000


@profile_bp.route("/resettoken", methods=["GET", "POST"])
@login_required
def reset_token():
    if request.method == "POST":
        token = request.form.get("token")
        if token != current_user.auth_token:
            raise BadRequest("Can only reset token of currently logged in user")
        reset = request.form.get("reset")
        if reset == "yes":
            try:
                db_user.update_token(current_user.id)
                flash.info("Access token reset")
            except DatabaseException:
                flash.error("Something went wrong! Unable to reset token right now.")
        return redirect(url_for("profile.info"))
    else:
        token = current_user.auth_token
        return render_template(
            "user/resettoken.html",
            token=token,
        )


@profile_bp.route("/resetlatestimportts", methods=["GET", "POST"])
@login_required
def reset_latest_import_timestamp():
    if request.method == "POST":
        token = request.form.get("token")
        if token != current_user.auth_token:
            raise BadRequest("Can only reset latest import timestamp of currently logged in user")
        reset = request.form.get("reset")
        if reset == "yes":
            try:
                db_user.reset_latest_import(current_user.musicbrainz_id)
                flash.info("Latest import time reset, we'll now import all your data instead of stopping at your last imported listen.")
            except DatabaseException:
                flash.error("Something went wrong! Unable to reset latest import timestamp right now.")
        return redirect(url_for("profile.info"))
    else:
        token = current_user.auth_token
        return render_template(
            "profile/resetlatestimportts.html",
            token=token,
        )


@profile_bp.route("/")
@login_required
def info():

    return render_template(
        "profile/info.html",
        user=current_user
    )


@profile_bp.route("/import")
@login_required
def import_data():
    """ Displays the import page to user, giving various options """

    # Return error if LASTFM_API_KEY is not given in config.py
    if 'LASTFM_API_KEY' not in current_app.config or current_app.config['LASTFM_API_KEY'] == "":
        return NotFound("LASTFM_API_KEY not specified.")

    user_data = {
        "id": current_user.id,
        "name": current_user.musicbrainz_id,
        "auth_token": current_user.auth_token,
    }

    props = {
        "user": user_data,
        "profile_url": url_for('user.profile', user_name=user_data["name"]),
        "api_url":  current_app.config["API_URL"],
        "lastfm_api_url": current_app.config["LASTFM_API_URL"],
        "lastfm_api_key": current_app.config["LASTFM_API_KEY"],
    }

    return render_template(
        "user/import.html",
        user=current_user,
        props=ujson.dumps(props),
    )


def fetch_listens(musicbrainz_id, to_ts, time_range=None):
    """
    Fetch all listens for the user from listenstore by making repeated queries
    to listenstore until we get all the data. Returns a generator that streams
    the results.
    """
    db_conn = webserver.create_timescale(current_app)
    while True:
        batch = db_conn.fetch_listens(current_user.musicbrainz_id, to_ts=to_ts, limit=EXPORT_FETCH_COUNT, time_range=time_range)
        if not batch:
            break
        yield from batch
        to_ts = batch[-1].ts_since_epoch  # new to_ts will be the the timestamp of the last listen fetched


def fetch_feedback(user_id):
    """
    Fetch feedback by making repeated queries to DB until we get all the data.
    Returns a generator that streams the results.
    """
    batch = []
    offset = 0
    while True:
        batch = db_feedback.get_feedback_for_user(user_id=current_user.id, limit=EXPORT_FETCH_COUNT, offset=offset)
        if not batch:
            break
        yield from batch
        offset += len(batch)


def stream_json_array(elements):
    """ Return a generator of string fragments of the elements encoded as array. """
    for i, element in enumerate(elements):
        yield '[' if i == 0 else ','
        yield ujson.dumps(element)
    yield ']'


@profile_bp.route("/export", methods=["GET", "POST"])
@login_required
def export_data():
    """ Exporting the data to json """
    if request.method == "POST":
        db_conn = webserver.create_timescale(current_app)
        filename = current_user.musicbrainz_id + "_lb-" + datetime.today().strftime('%Y-%m-%d') + ".json"

        # Build a generator that streams the json response. We never load all
        # listens into memory at once, and we can start serving the response
        # immediately.
        to_ts = int(time())
        listens = fetch_listens(current_user.musicbrainz_id, to_ts, time_range=-1)
        output = stream_json_array(listen.to_api() for listen in listens)

        response = Response(stream_with_context(output))
        response.headers["Content-Disposition"] = "attachment; filename=" + filename
        response.headers['Content-Type'] = 'application/json; charset=utf-8'
        response.mimetype = "text/json"
        return response
    else:
        return render_template("user/export.html", user=current_user)


@profile_bp.route("/export-feedback", methods=["POST"])
@login_required
def export_feedback():
    """ Exporting the feedback data to json """
    filename = current_user.musicbrainz_id + "_lb_feedback-" + datetime.today().strftime('%Y-%m-%d') + ".json"

    # Build a generator that streams the json response. We never load all
    # feedback into memory at once, and we can start serving the response
    # immediately.
    feedback = fetch_feedback(current_user.id)
    output = stream_json_array(_feedback_to_api(fb=fb) for fb in feedback)

    response = Response(stream_with_context(output))
    response.headers["Content-Disposition"] = "attachment; filename=" + filename
    response.headers['Content-Type'] = 'application/json; charset=utf-8'
    response.mimetype = "text/json"
    return response


@profile_bp.route('/delete', methods=['GET', 'POST'])
@login_required
def delete():
    """ Delete currently logged-in user from ListenBrainz.

    If POST request, this view checks for the correct authorization token and
    deletes the user. If deletion is successful, redirects to home page, else
    flashes an error and redirects to user's info page.

    If GET request, this view renders a page asking the user to confirm
    that they wish to delete their ListenBrainz account.
    """
    if request.method == 'POST':
        if request.form.get('token') == current_user.auth_token:
            try:
                delete_user(current_user.musicbrainz_id)
            except Exception as e:
                current_app.logger.error('Error while deleting %s: %s', current_user.musicbrainz_id, str(e))
                flash.error('Error while deleting user %s, please try again later.' % current_user.musicbrainz_id)
                return redirect(url_for('profile.info'))
            return redirect(url_for('index.index'))
        else:
            flash.error('Cannot delete user due to error during authentication, please try again later.')
            return redirect(url_for('profile.info'))
    else:
        return render_template(
            'profile/delete.html',
            user=current_user,
        )

@profile_bp.route('/delete-listens', methods=['GET', 'POST'])
@login_required
def delete_listens():
    """ Delete all the listens for the currently logged-in user from ListenBrainz.

    If POST request, this view checks for the correct authorization token and
    deletes the listens. If deletion is successful, redirects to user's profile page,
    else flashes an error and redirects to user's info page.

    If GET request, this view renders a page asking the user to confirm that they
    wish to delete their listens.
    """
    if request.method == 'POST':
        if request.form.get('token') and (request.form.get('token') == current_user.auth_token):
            try:
                delete_listens_history(current_user.musicbrainz_id)
            except Exception as e:
                current_app.logger.error('Error while deleting listens for %s: %s', current_user.musicbrainz_id, str(e))
                flash.error('Error while deleting listens for %s, please try again later.' % current_user.musicbrainz_id)
                return redirect(url_for('profile.info'))

listenbrainz/webserver/templates/profile/delete.html
{% extends 'base.html' %}

{% block title %}Delete account - ListenBrainz{% endblock %}

{% block content %}
  <h3 class="page-title">Delete your account</h3>
  <p>Hi {{ user.musicbrainz_id }}, are you sure you want to delete your ListenBrainz account? </p>

  <p>
    Once deleted, all your ListenBrainz data will be removed PERMANENTLY and will not be recoverable.
  </p>

  <p> Note: you can export your ListenBrainz data before deleting your account. </p>

  <form action="{{url_for("profile.export_data")}}" method='POST'>
    <button class="btn btn-warning btn-lg" type="submit" style="width: 250px">Export my listens.</button>
  </form>

  <form action="{{url_for("profile.export_feedback")}}" method='POST'>
    <button class="btn btn-warning btn-lg" type="submit" style="width: 250px">Export my feedback.</button>
  </form>

  <form method="post">
    <input type="hidden" name="token" value="{{ user.auth_token }}">
    <button id="btn-delete-user" class="btn btn-danger btn-lg" style="width: 250px">Delete my account.</button>
  </form>
{% endblock %}

listenbrainz/webserver/templates/profile/delete_listens.html
{% extends 'base.html' %}

{% block title %}Delete listens - ListenBrainz{% endblock %}

{% block content %}
<h3 class="page-title">Delete your listens</h3>
<p>Hi {{ user.musicbrainz_id }}, are you sure you want to delete listens imported into your ListenBrainz account? </p>

<p>
    Once deleted, all your listens data will be removed PERMANENTLY.
</p>

<p> Note: you can export your ListenBrainz data before deleting your listens. </p>

<form action="{{url_for("profile.export_data")}}" method='POST'>
    <button class="btn btn-warning btn-lg" type="submit" style="width: 250px">Export my listens.</button>
</form>
<br>
<p>
    Yes, I am sure I want to erase my entire listening history
</p>
<form method="post">
    <input type="hidden" name="token" value="{{ user.auth_token }}">
    <button id="btn-delete-listens" class="btn btn-danger btn-lg" style="width: 250px">Delete my listens.</button>
</form>
{% endblock %}

listenbrainz/webserver/templates/profile/info.html
{% extends 'base.html' %}

{% block title %}User "{{ user.musicbrainz_id }}" - ListenBrainz{% endblock %}

{% block content %}
  <div id="user-profile">
    <h2 class="page-title">{{ user.musicbrainz_id }}</h2>

    <h3> Delete your account </h3>

    <p>
      <a href="{{ url_for("profile.delete") }}" style="color: white;"><span class="btn btn-info btn-lg" style="width: 300px">Delete your account</span></a>
    </p>

    <h3> Delete your listens </h3>
    <p>
      This will delete all your listens imported into Listenbrainz.
    </p>

    <p>
      <a href="{{ url_for("profile.delete_listens") }}" style="color: white;"><span class="btn btn-info btn-lg" style="width: 300px">Delete your listens</span></a>
    </p>

    <h3> Reset Last.FM Import timestamp </h3>
    <p>
      If you think that a partial import has somehow missed some listens, you may reset your previous
      import timestamp. This will cause your next import to be a complete import which should add any
      missing listens while still avoiding adding duplicates to your history.
    </p>

    <p>If you want to reset your previous import timestamp, click below</p>
    <p>
      <span class="btn btn-info btn-lg" style="width: 300px"><a href="{{ url_for("profile.reset_latest_import_timestamp") }}" style="color: white;">Reset Import Timestamp</a></span>
    </p>

    <h3>User token</h3>
    <p>
      If you would like to use an external program to submit data to ListenBrainz, you will need the following user token:
    </p>

    <p>
      <form class="form-inline">
        <input type="password" class="form-control" id="auth-token" style="width: 400px; height:30px;" value="{{ user.auth_token }}" readonly />
        <button type="button" class="btn btn-info glyphicon glyphicon-eye-open" id="show-hide-token" style="width: 50px; height:30px; top: 0px;" title="Show user token"></button>
        <button type="button" class="btn btn-info" id="copy-token" style="width: 90px; height:30px;" title="Copy user token">Copy</button>
      </form>
    </p>

    <p>If you want to reset your token, click below</p>
    <p>
      <span class="btn btn-info btn-lg" style="width: 200px"><a href="{{ url_for("profile.reset_token") }}" style="color: white;">Reset token</a></span>
    </p>

  </div>

{% endblock %}

{% block scripts %}
  {{ super() }}
  <script src="{{ url_for('static', filename='js/info.js') }}"></script>
{% endblock %}

listenbrainz/webserver/templates/profile/resetlatestimportts.html
{% extends 'base.html' %}

{% block title %}Reset import timestamp- ListenBrainz{% endblock %}

{% block content %}
  <h3 class="page-title">Reset Import Timestamp</h3>
  <p>Are you sure you want to reset your import timestamp? </p>

  <p>
     Our last.fm importer keeps track of the listens you've imported and then only imports
     new listens added after previous imports. To do this, we keep track of the timestamp of
     the newest listen submitted in your last.fm import. By resetting this timestamp, you'll
     be able to import your entire last.fm data again. However, this will not create duplicates in
     your ListenBrainz listen history.
  </p>

  <form method="post">
      <input type="hidden" name="reset" value="yes">
      <input type="hidden" name="token" value="{{ token }}">
      <p>
         <button type="submit" class="btn btn-info btn-lg" style="width: 200px">Yes, reset it.</button>
      <p>
  </form>

{% endblock %}