listenbrainz/webserver/admin/__init__.py
from flask_admin import BaseView, AdminIndexView as IndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user
from flask import redirect, url_for, current_app

from listenbrainz.webserver import flash


class AuthMixin:
    """All admin views that shouldn't be available to the public must inherit from this."""

    def is_accessible(self):
        if current_user.is_authenticated:
            if current_user.musicbrainz_id in current_app.config['ADMINS']:
                return True
        return False

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            flash.error('You are not authorized to view the admin page.')
            return redirect(url_for('login.index'))

class AdminBaseView(AuthMixin, BaseView): pass
class AdminModelView(AuthMixin, ModelView): pass
class AdminIndexView(AuthMixin, IndexView): pass

listenbrainz/webserver/admin/views.py
from flask_admin import expose
from listenbrainz.webserver.admin import AdminIndexView


class HomeView(AdminIndexView):

    @expose('/')
    def index(self):
        return self.render('admin/home.html')

listenbrainz/webserver/login/__init__.py
from flask import redirect, url_for, current_app, request
from flask_login import LoginManager, UserMixin, current_user
from functools import wraps
import listenbrainz.db.user as db_user
from werkzeug.exceptions import Unauthorized
from listenbrainz.webserver.errors import APIUnauthorized

login_manager = LoginManager()
login_manager.login_view = 'login.index'


class User(UserMixin):
    def __init__(self, id, created, musicbrainz_id, auth_token, gdpr_agreed, login_id):
        self.id = id
        self.created = created
        self.musicbrainz_id = musicbrainz_id
        self.auth_token = auth_token
        self.gdpr_agreed = gdpr_agreed
        self.login_id = login_id

    def get_id(self):
        return self.login_id

    @classmethod
    def from_dbrow(cls, user):
        return cls(
            id=user['id'],
            created=user['created'],
            musicbrainz_id=user['musicbrainz_id'],
            auth_token=user['auth_token'],
            gdpr_agreed=user['gdpr_agreed'],
            login_id=user['login_id'],
        )

@login_manager.user_loader
def load_user(user_login_id):
    try:
        user = db_user.get_by_login_id(user_login_id)
    except Exception as e:
        current_app.logger.error("Error while getting user by login ID: %s", str(e), exc_info=True)
        return None
    if user:
        return User.from_dbrow(user)
    else:
        return None


def login_forbidden(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_anonymous:
            return redirect(url_for('index.index'))
        return f(*args, **kwargs)

    return decorated


def api_login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_authenticated:
            raise APIUnauthorized("You must be logged in to access this endpoint")
        return f(*args, **kwargs)

    return decorated

listenbrainz/webserver/views/follow.py
import ujson
from flask import Blueprint, render_template, current_app
from flask_login import current_user, login_required
from listenbrainz.domain import spotify
from listenbrainz.webserver.views.api_tools import parse_param_list
import listenbrainz.db.follow_list as db_follow_list


follow_bp = Blueprint("follow", __name__)

@follow_bp.route("/", defaults={"user_list": ""})
@follow_bp.route("/<user_list>")
@login_required
def follow(user_list):
    """ Allow an LB user to follow the stream of one or more other LB users.
    """

    if user_list:
        default_list = {'name': ''}
        follow_list_members = parse_param_list(user_list)
    else:
        default_list = db_follow_list.get_latest(creator=current_user.id)
        if not default_list:
            default_list = {'name': '', 'members': []}
        follow_list_members = [member['musicbrainz_id'] for member in default_list['members']]

    user_data = {
        "id": current_user.id,
        "name": current_user.musicbrainz_id,
        "auth_token": current_user.auth_token,
    }
    spotify_data = spotify.get_user_dict(current_user.id)
    props = {
        "user": user_data,
        "mode": "follow",
        "follow_list": follow_list_members,
        "spotify": spotify_data,
        "web_sockets_server_url": current_app.config["WEBSOCKETS_SERVER_URL"],
        "api_url": current_app.config["API_URL"],
        "save_url": "{}/1/follow/save".format(current_app.config["API_URL"]),
        "follow_list_name": default_list["name"],
        "follow_list_id": default_list["id"] if "id" in default_list else None,
    }

    return render_template(
        "index/follow.html",
        props=ujson.dumps(props),
        mode='follow',
        user=current_user,
        follow_list=follow_list_members,
        active_section='listens',
    )

listenbrainz/webserver/views/follow_api.py
import ujson
import listenbrainz.db.follow_list as db_follow_list
import listenbrainz.db.user as db_user

from flask import Blueprint, request, jsonify
from listenbrainz.webserver.decorators import crossdomain
from listenbrainz.webserver.rate_limiter import ratelimit
from listenbrainz.webserver.views.api_tools import log_raise_400, validate_auth_header
from listenbrainz.webserver.errors import APINotFound, APIForbidden, APIUnauthorized
from listenbrainz.db.exceptions import DatabaseException

follow_api_bp = Blueprint('follow_api_v1', __name__)

@follow_api_bp.route("/save", methods=["POST", "OPTIONS"])
@crossdomain(headers="Authorization, Content-Type")
@ratelimit()
def save_list():
    creator = validate_auth_header()
    raw_data = request.get_data()
    try:
        data = ujson.loads(raw_data.decode("utf-8"))
    except ValueError as e:
        log_raise_400("Cannot parse JSON document: %s" % str(e), raw_data)

    try:
        list_name = data['name']
        list_id = data['id']
        members = data['users']
    except KeyError as e:
        log_raise_400("JSON missing key: %s" % str(e))

    members = db_user.validate_usernames(members)
    if list_id is None:
        # create a new list
        try:
            list_id = db_follow_list.save(
                name=list_name,
                creator=creator['id'],
                members=[member['id'] for member in members],
            )
        except DatabaseException as e:
            raise APIForbidden("List with same name already exists.")
    else:

        # do some validation
        current_list = db_follow_list.get(list_id)
        if current_list is None:
            raise APINotFound("List not found: %d" % list_id)
        if current_list['creator'] != creator['id']:
            raise APIUnauthorized("You can only edit your own lists.")

        # update the old list
        db_follow_list.update(
            list_id=list_id,
            name=list_name,
            members=[member['id'] for member in members],
        )

    return jsonify({
        "code": 200,
        "message": "it worked!",
        "list_id": list_id,
    })

listenbrainz/webserver/views/index.py
import locale
import os
import requests
import subprocess

from brainzutils import cache
from datetime import datetime
from dateutil.relativedelta import relativedelta
from typing import List
from flask import Blueprint, render_template, current_app, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
from requests.exceptions import HTTPError
import ujson
from werkzeug.exceptions import Unauthorized, NotFound

import listenbrainz.db.user as db_user
from listenbrainz.db.exceptions import DatabaseException
from listenbrainz.domain import spotify
from listenbrainz import webserver
from listenbrainz.webserver import flash
from listenbrainz.webserver.timescale_connection import _ts
from listenbrainz.webserver.redis_connection import _redis
from listenbrainz.webserver.views.user import delete_user


index_bp = Blueprint('index', __name__)
locale.setlocale(locale.LC_ALL, '')

STATS_PREFIX = 'listenbrainz.stats' # prefix used in key to cache stats
CACHE_TIME = 10 * 60 # time in seconds we cache the stats
NUMBER_OF_RECENT_LISTENS = 50

@index_bp.route("/")
def index():

    # get total listen count
    try:
        listen_count = _ts.get_total_listen_count()
    except Exception as e:
        current_app.logger.error('Error while trying to get total listen count: %s', str(e))
        listen_count = None


    return render_template(
        "index/index.html",
        listen_count=listen_count,
    )


@index_bp.route("/import")
def import_data():
    if current_user.is_authenticated:
        return redirect(url_for("profile.import_data"))
    else:
        return current_app.login_manager.unauthorized()


@index_bp.route("/download")
def downloads():
    return redirect(url_for('index.data'))


@index_bp.route("/data")
def data():
    return render_template("index/data.html")


@index_bp.route("/contribute")
def contribute():
    return render_template("index/contribute.html")


@index_bp.route("/add-data")
def add_data_info():
    return render_template("index/add-data.html")


@index_bp.route("/import-data")
def import_data_info():
    return render_template("index/import-data.html")


@index_bp.route("/goals")
def goals():
    return render_template("index/goals.html")


@index_bp.route("/faq")
def faq():
    return render_template("index/faq.html")


@index_bp.route("/lastfm-proxy")
def proxy():
    return render_template("index/lastfm-proxy.html")


@index_bp.route("/roadmap")
def roadmap():
    return render_template("index/roadmap.html")


@index_bp.route("/current-status")
def current_status():

    load = "%.2f %.2f %.2f" % os.getloadavg()

    listen_count = _ts.get_total_listen_count()
    try:
        user_count = format(int(_get_user_count()), ',d')
    except DatabaseException as e:
        user_count = 'Unknown'

    listen_counts_per_day: List[dict] = []
    for delta in range(2):
        try:
            day = datetime.utcnow() - relativedelta(days=delta)
            day_listen_count = _redis.get_listen_count_for_day(day)
        except:
            current_app.logger.error("Could not get %s listen count from redis", day.strftime('%Y-%m-%d'), exc_info=True)
            day_listen_count = None
        listen_counts_per_day.append({
            "date": day.strftime('%Y-%m-%d'),
            "listen_count": format(day_listen_count, ',d') if day_listen_count else "0",
            "label": "today" if delta == 0 else "yesterday",
        })

    return render_template(
        "index/current-status.html",
        load=load,
        listen_count=format(int(listen_count), ",d") if listen_count else "0",
        user_count=user_count,
        listen_counts_per_day=listen_counts_per_day,
    )


@index_bp.route("/recent")
def recent_listens():

    recent = []
    for listen in _redis.get_recent_listens(NUMBER_OF_RECENT_LISTENS):
        recent.append({
                "track_metadata": listen.data,
                "user_name" : listen.user_name,
                "listened_at": listen.ts_since_epoch,
                "listened_at_iso": listen.timestamp.isoformat() + "Z",
            })

    spotify_user = {}
    if current_user.is_authenticated:
        spotify_user = spotify.get_user_dict(current_user.id)

    props = {
        "listens": recent,
        "mode": "recent",
        "spotify": spotify_user,
        "api_url": current_app.config["API_URL"],
    }

    return render_template("index/recent.html",
        props=ujson.dumps(props),
        mode='recent',
        active_section='listens')

@index_bp.route('/feed', methods=['GET', 'OPTIONS'])
@login_required
def feed():

    # TODO (param): remove this when feed feature is ready for release #feedfeatureflag
    if current_user.musicbrainz_id not in ['rob', 'iliekcomputers', 'mr_monkey', 'shivam-kapila', 'ishaanshah']:
        raise NotFound

    props = {
        'current_user': {
            'id': current_user.id,
            'name': current_user.musicbrainz_id,
            'auth_token': current_user.auth_token,
        }
    }
    return render_template('index/feed.html', props=ujson.dumps(props))



@index_bp.route('/agree-to-terms', methods=['GET', 'POST'])
@login_required
def gdpr_notice():
    if request.method == 'GET':
        return render_template('index/gdpr.html', next=request.args.get('next'))
    elif request.method == 'POST':
        if request.form.get('gdpr-options') == 'agree':
            try:
                db_user.agree_to_gdpr(current_user.musicbrainz_id)
            except DatabaseException as e:
                flash.error('Could not store agreement to GDPR terms')
            next = request.form.get('next')
            if next:
                return redirect(next)
            return redirect(url_for('index.index'))
        elif request.form.get('gdpr-options') == 'disagree':
            return redirect(url_for('profile.delete'))
        else:
            flash.error('You must agree to or decline our terms')
            return render_template('index/gdpr.html', next=request.args.get('next'))


@index_bp.route('/delete-user/<int:musicbrainz_row_id>')
def mb_user_deleter(musicbrainz_row_id):
    """ This endpoint is used by MusicBrainz to delete accounts once they
    are deleted on MusicBrainz too.

    See https://tickets.metabrainz.org/browse/MBS-9680 for details.

    Args: musicbrainz_row_id (int): the MusicBrainz row ID of the user to be deleted.

    Returns: 200 if the user has been successfully found and deleted from LB

    Raises:
        NotFound if the user is not found in the LB database
        Unauthorized if the MusicBrainz access token provided with the query is invalid
    """
    _authorize_mb_user_deleter(request.args.get('access_token', ''))
    user = db_user.get_by_mb_row_id(musicbrainz_row_id)
    if user is None:
        raise NotFound('Could not find user with MusicBrainz Row ID: %d' % musicbrainz_row_id)
    delete_user(user['musicbrainz_id'])
    return jsonify({'status': 'ok'}), 200


def _authorize_mb_user_deleter(auth_token):
    headers = {'Authorization': 'Bearer {}'.format(auth_token)}
    r = requests.get(current_app.config['MUSICBRAINZ_OAUTH_URL'], headers=headers)
    try:
        r.raise_for_status()
    except HTTPError:
        raise Unauthorized('Not authorized to use this view')

    data = {}
    try:
        data = r.json()
    except ValueError:
        raise Unauthorized('Not authorized to use this view')

    try:
        # 2007538 is the row ID of the `UserDeleter` account that is
        # authorized to access the `delete-user` endpoint
        if data['sub'] != 'UserDeleter' or data['metabrainz_user_id'] != 2007538:
            raise Unauthorized('Not authorized to use this view')
    except KeyError:
        raise Unauthorized('Not authorized to use this view')


def _get_user_count():
    """ Gets user count from either the brainzutils cache or from the database.
        If not present in the cache, it makes a query to the db and stores the
        result in the cache for 10 minutes.
    """
    user_count_key = "{}.{}".format(STATS_PREFIX, 'user_count')
    user_count = cache.get(user_count_key, decode=False)
    if user_count:
        return user_count
    else:
        try:
            user_count = db_user.get_user_count()
        except DatabaseException as e:
            raise
        cache.set(user_count_key, int(user_count), CACHE_TIME, encode=False)
        return user_count

listenbrainz/webserver/views/login.py
from flask import Blueprint, request, redirect, render_template, url_for, session, current_app
from flask_login import login_user, logout_user, login_required
from listenbrainz.webserver.login import login_forbidden, provider
from listenbrainz.webserver import flash
import listenbrainz.db.user as db_user
import time
import datetime

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
@login_forbidden
def index():
    return render_template('login/login.html')


@login_bp.route('/musicbrainz')
@login_forbidden
def musicbrainz():
    session['next'] = request.args.get('next')
    return redirect(provider.get_authentication_uri())


@login_bp.route('/musicbrainz/post')
@login_forbidden
def musicbrainz_post():
    """Callback endpoint."""
    if provider.validate_post_login():
        user = provider.get_user()
        db_user.update_last_login(user.musicbrainz_id)
        login_user(user, remember=True, duration=datetime.timedelta(current_app.config['SESSION_REMEMBER_ME_DURATION']))
        next = session.get('next')
        if next:
            return redirect(next)
    else:
        flash.error("Login failed.")
    return redirect(url_for('index.index'))


@login_bp.route('/logout/')
@login_required
def logout():
    session.clear()
    logout_user()
    return redirect(url_for('index.index'))

listenbrainz/webserver/templates/base-react.html
{% extends 'base.html' %}

{% block content %}
    <div id="react-container">
    </div>
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script id="react-props" type="application/json">{{ props|safe }}</script>
{% endblock %}

listenbrainz/webserver/templates/base.html
{% from 'macros.html' import print_message %}

<!DOCTYPE html>
<html>
<head>
  {%- block head -%}
    <meta charset="utf-8" />
    <title>{% block title %}ListenBrainz{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="icon" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16.png') }}" type="image/png" />
    <link rel="icon" sizes="256x256" href="{{ url_for('static', filename='img/favicon-256.png') }}" type="image/png" />
    <link rel="icon" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32.png') }}" type="image/png" />

    {% if config.COMPILE_LESS %}
      <link href="{{ url_for('static', filename='css/main.less') }}" rel="stylesheet/less" type="text/css" />
      <script src="{{ url_for('static', filename='js/lib/less.min.js') }}"></script>
    {% else %}
      <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" media="screen" />
    {% endif %}
  {%- endblock -%}
</head>

<body>
  {%- include 'navbar.html' -%}

  <div class="container">

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% for category, message in messages %}
        {{ print_message(message, category) }}
      {% endfor %}
    {% endwith %}

    {%- block wrapper -%}
    <div class ="wrapper">

      {%- block content -%}
      <!-- Page content -->
      {%- endblock -%}
    </div>
    {%- endblock -%}

    {%- block footer -%}
    <div class="footer">
      <hr />
        <ul class="list-inline pull-left">
          <li><a href="http://blog.musicbrainz.org/category/listenbrainz/">Blog</a></li>
          <li><a href="https://twitter.com/ListenBrainz">Twitter</a></li>
          <li><a href="https://github.com/metabrainz/listenbrainz-server/">GitHub</a></li>
          <li><a href="http://tickets.musicbrainz.org/browse/LB">Bug Tracker</a></li>
          <li><a href="{{ url_for("index.current_status") }}">Status</a></li>
        </ul>
        <ul class="list-inline pull-right">
          <li><a href="https://metabrainz.org" title="MetaBrainz"><img src="{{ url_for('static', filename='img/MetaBrainz_logo_no_text.svg') }}" /></a></li>
        </ul>
      </div>
    {%- endblock -%}
  </div>

  {%- block scripts -%}
    <script src="{{ url_for('static', filename='js/lib/jquery-2.1.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/lib/bootstrap.min.js') }}"></script>
  {%- endblock -%}
</body>
</html>

listenbrainz/webserver/templates/macros.html
{% macro print_message(message, category) %}
  {% if category == "error" %}
    {% set alert_class="alert-danger" %}
  {% elif category == "warning" %}
    {% set alert_class="alert-warning" %}
  {% elif category == "success" %}
    {% set alert_class="alert-success" %}
  {% else %} {# info & default #}
    {% set alert_class="alert-info" %}
  {% endif %}

  <div class="alert {{ alert_class }}">{{ message }}</div>
{% endmacro %}

listenbrainz/webserver/templates/navbar.html
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">

    {#- Brand and toggle get grouped for better mobile display -#}
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#lb-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo" href="{{ url_for('index.index') }}">
          <img src="{{ url_for('static', filename='img/navbar_logo.svg') }}" alt="ListenBrainz" />
      </a>
    </div>

    {#- Collect the nav links, forms, and other content for toggling -#}
    <div class="collapse navbar-collapse" id="lb-navbar-collapse">
      <ul class="nav navbar-nav">
        {% if not hide_navbar_user_menu %}
          {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('user.profile', user_name=current_user.musicbrainz_id) }}">My Listens</a></li>
            <li><a href="{{ url_for('follow.follow') }}">Follow</a></li>
          {% endif %}
        {%- endif -%}
        <li><a href="{{ url_for('index.recent_listens') }}">Recent</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
             About<span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{{ url_for('index.faq') }}">FAQ</a></li>
            <li><a href="{{ url_for('index.goals') }}">Goals</a></li>
            <li><a href="{{ url_for('index.roadmap') }}">Roadmap</a></li>
            <li><a href="https://listenbrainz.readthedocs.io">API Docs</a></li>
            <li><a href="{{ url_for('index.contribute') }}">Contribute</a></li>
            <li><a href="{{ url_for('index.current_status') }}">Current site status</a></li>
            <li><a href="https://metabrainz.org/gdpr">GDPR compliance</a></li>
            <li><a href="https://metabrainz.org/privacy">Privacy policy</a></li>
            <li><a href="https://metabrainz.org">About MetaBrainz</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
             Data<span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{{ url_for('index.add_data_info') }}">Adding data</a></li>
            <li><a href="{{ url_for('index.import_data_info') }}">Importing data</a></li>
            <li><a href="{{ url_for('index.data') }}">Using our data</a></li>
          </ul>
        </li>
    </ul>

    {% if not hide_navbar_user_menu %}
      <ul class="nav navbar-nav navbar-right">
        {% if not current_user.is_authenticated or current_user.is_anonymous %}
          <li>
            <a href="{{ url_for('login.index') }}">Sign in</a>
          </li>
        {% else %}
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              {{ current_user.musicbrainz_id }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{{ url_for('user.profile', user_name=current_user.musicbrainz_id) }}">My Listens</a></li>
              {% if config.get('FEATURE_PLAYLIST') %}
              <li><a href="{{ url_for('user.playlists', user_name=current_user.musicbrainz_id) }}">My Playlists</a></li>
              {% endif %}
              <li><a href="{{ url_for('recommendations_cf_recording.info', user_name=current_user.musicbrainz_id) }}">Tracks you might like</a></li>
              <li><a href="{{ url_for('profile.connect_spotify') }}">Connect Spotify</a></li>
              <li><a href="{{ url_for('profile.import_data') }}">Import listens</a></li>
              <li><a href="{{ url_for('profile.export_data') }}">Export</a></li>
              <li><a href="{{ url_for('profile.info') }}">My profile</a></li>
              <li><a href="{{ url_for('login.logout') }}">Sign out</a></li>
            </ul>
          </li>
        {%- endif -%}
      </ul>
    {% endif %}
    </div>

  </div>
</nav>